### ISSUE TITLE
proposal: become a more pro extension

### ISSUE THREAD

**Issue by ylc395** [benlau/memoinjo#1]
Would it be nice if we add more functions into this extension? Just like this:

https://addons.mozilla.org/en-US/firefox/addon/textmarkerpro/

If this is acceptable, I will do some contribution to this project.

**Comment by benlau** [comment]
hi @ylc395 

Thank for your suggestion. I never used textmarkerpro before. Do you mean to add a feature to highlight and capture text on a web site and store in Joplin? If yes, I think it is a bit over kill for this extension. I would like to improve the text editor but I don't want to ask for more permission from user as MemoInjo is not a web clipper.
